- hosts: all
  remote_user: ec2-user
  become: yes
  tasks:
    - name: Installing apache
      yum:
        name: httpd
        state: present

    - name: Starting apache service
      service:
        name: httpd
        state: started
